#include "visualize.h"

#include <string>
#include <vector>

// COCO Class names
// Index of the class in the list is its ID. For example, to get ID of
// the teddy bear class, use: class_names.index("teddy bear")
static std::vector<std::string> class_names = {"BG",
                                               "person",
                                               "bicycle",
                                               "car",
                                               "motorcycle",
                                               "airplane",
                                               "bus",
                                               "train",
                                               "truck",
                                               "boat",
                                               "traffic light",
                                               "fire hydrant",
                                               "stop sign",
                                               "parking meter",
                                               "bench",
                                               "bird",
                                               "cat",
                                               "dog",
                                               "horse",
                                               "sheep",
                                               "cow",
                                               "elephant",
                                               "bear",
                                               "zebra",
                                               "giraffe",
                                               "backpack",
                                               "umbrella",
                                               "handbag",
                                               "tie",
                                               "suitcase",
                                               "frisbee",
                                               "skis",
                                               "snowboard",
                                               "sports ball",
                                               "kite",
                                               "baseball bat",
                                               "baseball glove",
                                               "skateboard",
                                               "surfboard",
                                               "tennis racket",
                                               "bottle",
                                               "wine glass",
                                               "cup",
                                               "fork",
                                               "knife",
                                               "spoon",
                                               "bowl",
                                               "banana",
                                               "apple",
                                               "sandwich",
                                               "orange",
                                               "broccoli",
                                               "carrot",
                                               "hot dog",
                                               "pizza",
                                               "donut",
                                               "cake",
                                               "chair",
                                               "couch",
                                               "potted plant",
                                               "bed",
                                               "dining table",
                                               "toilet",
                                               "tv",
                                               "laptop",
                                               "mouse",
                                               "remote",
                                               "keyboard",
                                               "cell phone",
                                               "microwave",
                                               "oven",
                                               "toaster",
                                               "sink",
                                               "refrigerator",
                                               "book",
                                               "clock",
                                               "vase",
                                               "scissors",
                                               "teddy bear",
                                               "hair drier",
                                               "toothbrush"};

Visualize::Visualize() {}
